mkdir -p stitch_output/screenshots
mkdir -p stitch_output/html

# Home: Reflect
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ujNQgWqF6l5z3vq6ZKkL7jsH6pNaPgXiVaT9wXUg3axBhBn3vToQ2iXqAlgPedi25xZLWYM4b6F-VKRUcIJOSeKaSpOrv6A69R84wItD8I7QBeLR0LUAbXZIeHIJPQ_3n4iH1R-DZv_qzX8d2NMeqRBtrO5kTurWVD1AWJR09ARnZ-vRjKvLlSclUlpJ1qOSy7LAimE1WgHI8Bw-M6RL4nLPJ-1fF3es0-R9nxAORmJOKvMBpSyvAW6t1s" -o stitch_output/screenshots/home_reflect.png
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzYxYTQ5NTdhMjQ4ZTQxNzVhMDkwMjc0MWFiYzQxMmQxEgsSBxCw5oW2kAgYAZIBIwoKcHJvamVjdF9pZBIVQhM4NTExMDUyMjQ1MTYxNjAxOTc4&filename=&opi=89354086" -o stitch_output/html/home_reflect.html

# User Dashboard
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ugQSqp7RqWZ2p5jAFO0hibL9EbtsEmkp3N5BzQEnnhqm3XiMvbFGXkQ5169JcKwGBpKRKrHGTarykB8MxNh73VE6cb0-nhh-YBiF1Py1JUmBFzI1CZrvCXmUaV38f6XkzpRmxgUOLQ0pqu4nUgmNAqJNtpF3XfKx1texHUl0uKrP_CblI0__uoyrcZgQV84AuHck6taTdVUej7sIU3BrUhzExgN1y09_JLnxTvXzUsr_eT_Isk3Vs0luVM" -o stitch_output/screenshots/user_dashboard.png
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2JlZDdhM2EzMThkMzQyNzg4MDBmZGY3OGQ1NjU1NTAxEgsSBxCw5oW2kAgYAZIBIwoKcHJvamVjdF9pZBIVQhM4NTExMDUyMjQ1MTYxNjAxOTc4&filename=&opi=89354086" -o stitch_output/html/user_dashboard.html

# Courses Catalog
curl -L "https://lh3.googleusercontent.com/aida/ADBb0uh8TvaO8QMaBuBcRIzooYSinPiHbEHirvAcY6wKnU9OTItLIeJzzKMp-vSI34MU23XZnu0QGy5BeitNBZwXjIjzYxD5UmrUhfnON7yXlHJ4YNMCKwfr2FEIawZawrxjqSa8Zuo0QmcsbYGZcGKq5uMkG2iwfr9vHF8Xt9C417_vh2DNAeMcSNXNoHQ3yJBmLawga3lZzgOurT8gnoEW-0Pj_RKNiBTEYphPLxgCK0NXlJxBVhy-YcT7Pbg" -o stitch_output/screenshots/courses_catalog.png
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzk1OTNlMWI0YjMwOTRmMzc4MWQ3ZWRhYmNlODE5MzczEgsSBxCw5oW2kAgYAZIBIwoKcHJvamVjdF9pZBIVQhM4NTExMDUyMjQ1MTYxNjAxOTc4&filename=&opi=89354086" -o stitch_output/html/courses_catalog.html

# Dashboard: Visual Path
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ujV_7IKtK4-dxs5l90RyVQWuYgWQvV-VtJAT5tQ5p2Vx37_nG8j5QQdZwt_7QXcYU6cowhcPxYIvAdua_UH4T0Psum9KHdOy1zI7PCf15q8aOkfI178lo92UWxswa_Mxt7icdrtrts4lyRZ_gQVyMKd_k-LVX9FcEGJ8-zBGG0wrLnQ4Gh9H-Pesf47oC9RQigZHIOg6QoO2qDcvv_9WMkQGRtZS24vFsn53PARQsJCRBm2Z9aYKOUJC6A" -o stitch_output/screenshots/dashboard_visual_path.png
curl -L "https://contribution.usercontent.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzJlNWY5MmMyZWRlZDRiNGU5OWYxYmIzMDYxMWVkMjlhEgsSBxCw5oW2kAgYAZIBIwoKcHJvamVjdF9pZBIVQhM4NTExMDUyMjQ1MTYxNjAxOTc4&filename=&opi=89354086" -o stitch_output/html/dashboard_visual_path.html

# Dashboard: Deep Focus
curl -L "https://lh3.googleusercontent.com/aida/ADBb0uhKN3l03htKBi1rA-Nh4MwkifcnfWttosPN3p_m9_fGFiRqndu_xhJuyEobmpjD2tYUOyhXB2Mb5KQBAuPd7GugCWYtn_Z6nksOhSgd7eH0a3Fo2S_pgdPiXzmMhK7dCJOE-JgUV7SQ3K_OpKMBRkzx-yYUaCvFz_4KwrfgalNSaOJrUU5Iw_dAFUvU7b7tr9LdGBRaSfpXZzHTU0NvOfVA81zrC5ZEIEObXvUAiMPlHrSHuZDe1SBFQA" -o stitch_output/screenshots/dashboard_deep_focus.png
curl -L "https://contribution.usercontent.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzc0YmFhYjkwYmZjYjQ3YzViMGI5Nzc3NTg1MDQ2YjgyEgsSBxCw5oW2kAgYAZIBIwoKcHJvamVjdF9pZBIVQhM4NTExMDUyMjQ1MTYxNjAxOTc4&filename=&opi=89354086" -o stitch_output/html/dashboard_deep_focus.html

# Dashboard: Command Center
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ujoAcUY_gnqpz61fE5IPl5qKkeQSYGwbuoVYZJRQ7qi0pfcuQOHK__e7Rh9Mr19KQSpCr8v12_XoCZ-3YCN6WYd93i6H6wEuQhjWM3vhUmsNi8hSlp1TxQP9p-ZNvgPTN-A8o5l1HLP2XCUvSDAG5z6tfPwwdXh85KrBIAAa34cXr7thdGT3spD0YFMO-FOyL3dofPNVeO2URgbTIUJFfobGADtNHintZ6jutdwZ2N10H9Jmjjr_3vn7sU" -o stitch_output/screenshots/dashboard_command_center.png
curl -L "https://contribution.usercontent.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2I1M2EwNzY0ZWQ5MDQ2MTBhNjliODkyYzM0OTM3NzAwEgsSBxCw5oW2kAgYAZIBIwoKcHJvamVjdF9pZBIVQhM4NTExMDUyMjQ1MTYxNjAxOTc4&filename=&opi=89354086" -o stitch_output/html/dashboard_command_center.html

# Course Detail: Advanced DS
curl -L "https://lh3.googleusercontent.com/aida/ADBb0uhZFOaX5aB49_-crRIul4cwUcRlFqFcVf5SA0FWKBxb_N8ZQtaHYJUy0RxHq_v7FzrB6pjBsbFMALUsZURhwO9upQniVm-6ggW6Ym_6LXQYwq_mEKVpRS_UaDKBFNRk6mAanwTN882T_xXEf6m4KJsrs_aC7r_f2wDOeXNpT5d6KLnz53CbpaWVYpRkACRaI_K8eGKFtUxYFjyxpuotb3DuQXnQT3ZJVXxWzvnYUqBmV_FW6S9hr1am-lQ" -o stitch_output/screenshots/course_detail_advanced_ds.png
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzJhNWVhNjM3NjA5ODQ4ZmZiNTMyM2YyNTAyMWI3NTAyEgsSBxCw5oW2kAgYAZIBIwoKcHJvamVjdF9pZBIVQhM4NTExMDUyMjQ1MTYxNjAxOTc4&filename=&opi=89354086" -o stitch_output/html/course_detail_advanced_ds.html

